Lambda-School-Labs/best-places-to-live-fe

- src/Home/index.js
- src/Navigation/index.js
- src/TopTen/TopTenCards.js
- src/TopTen/index.js
> topten page refractored2.1

- src/Home/index.js
- src/HomeSearchBar/index.js
> Added search bar to home page

- src/App/routes.js
- src/Authorization/login.js
- src/Authorization/register.js
- src/Navigation/index.js
> Auth ui 2.2

- src/Authorization/login.js
* Needs to be deployed to testing env to be tested (link will not launch from a local env)
> changed endpoint for google auth in log-in component

- package.json
- src/Authorization/login.js
- src/TopTen/index.js
> Added auth/login onclick window.loc and added proxy to package.json

- src/TopTen/TopTenCards.js
- src/TopTen/index.js
added a conditional render in the top10list as well as images
> added a conditional render in the top10list as well as images

- src/Navigation/index.js
- src/Navigation/styled.js
> quick work of the sticky nav

- src/App/routes.js
- src/Dashboard/index.js
- src/Dashboard/profileSettings.js
- src/Dashboard/styled.js
> integration of sidenav bar and profile page into main dashboard component

- src/Dashboard/index.js
- src/Dashboard/profileSettings.js
- yarn.lock
Commented Profile Photo feature and Messages feature.
> Commented Profile Photo feature and Messages feature

- README.md
Branch didn't save update fro README
> Tried fixing README again, didn't take.

- src/HomeSearchBar/index.js
- src/UserList/index.css
> User list ui >merge conflict fix + padding adjustment for user search bar

- src/HomeSearchBar/index.js
- src/UserList/index.css
> Home bug fix

- src/Authorization/login.js
- src/TopTen/Back-side.js
- src/TopTen/TopTenCards.js
- src/TopTen/index.js
- src/TopTen/styled.js
- src/index.css
> Home page data input

- src/App/routes.js
- src/Authorization/register.js
- src/Dashboard/styled.js
- src/Navigation/styled.js
- yarn.lock
> Fixed cluster you know what

- src/HomeSearchBar/index.js
> Ol'reliable

- src/Authorization/login.js
- src/Navigation/index.js
- yarn.lock
- After a user successfully logins, the token returned is saved in to local storage.
- Logout button on navigation bar removes the token from localStorage.
> Login saves token to localStorage

- src/Authorization/register.js
- src/Dashboard/cityCard.js
- src/Dashboard/index.js
- src/Dashboard/passwordSettings.js
- src/Dashboard/profileSettings.js
- src/HomeSearchBar/index.js
Storing token on registration, Using token in Dashboard component to pre-populate forms with user info. fixed merge conflicts
> Refactor post crash

- src/Navigation/index.js
Logout button that removes token `letsmovehomie` from localStorage
> Logout button that removes token from localStorage

- src/Navigation/index.js
Login and Signup buttons only display when user is not logged in
`src/Navigation/index.js`
> Login and Signup buttons only display when user is not logged in

- src/Authorization/login.js
- src/GoogleMap/index.js
- src/HomeSearchBar/index.js
- src/Navigation/index.js
- src/UserList/components/users/User.js
- src/UserList/index.js
Warning errors removed from `src/UserList` and `src/GoogleMap` folder.
> Few Warning errors removed

- src/Authorization/login.js
- src/Authorization/register.js
- src/Authorization/styled.js
- src/HomeSearchBar/index.js
- src/TopTen/index.js
> User authentication maintnence

- package.json
- src/Navigation/index.js
- src/__tests__/jest/CategoryContent.test.js
- src/__tests__/jest/HomeSearchBar.js
- src/__tests__/jest/Navigation.test.js
- src/__tests__/jest/TopTen.test.js
- src/__tests__/jest/__snapshots__/CategoryContent.test.js.snap
- src/__tests__/jest/__snapshots__/HomeSearchBar.js.snap
- src/__tests__/jest/__snapshots__/Navigation.test.js.snap
- src/__tests__/jest/__snapshots__/TopTen.test.js.snap
- yarn.lock
Snapshot tests with jest. 
To run:
- yarn install
- yarn run test
> added snapshot testing with jest.

- src/App/routes.js
- src/CityDetail/CatagoryView.js
- src/CityDetail/CircleImage.js
- src/CityDetail/GraphView.js
- src/CityDetail/index.js
- src/GoogleMap/index.js
- src/Navigation/index.js
- src/Navigation/styled.js
- src/TopTen/index.js
First version of city details page. Also some updates to the map view page to help link the two pages together.
> City detail version 1

- src/App.js
- src/components/signUp.js
Works in browser along with validation. Connected to redux but action creator is not created.
Will also stop pushing App (with barely any changes).
> Finished SignUp

- src/components/PrivateRoute.js
Completed logic for private route (copy and paste...)
> Completed Private Route

- src/App.js
- src/components/login.js
- src/components/signUp.js
Finished login.
Works in browser. Connected to redux but no action creator "login" is actually made
> Feature login

- src/utils/axiosWithAuth.js
> Added backend base url to axios with auth

- src/components/Login.js
Co-authored-by: Nazifa Hossain <44625143+ampers-and@users.noreply.github.com>
Co-authored-by: Christopher Pupo <cpupo822@gmail.com>
> Login lfunctionality

- src/components/ExplorePage.js
- src/reducers/factors.js
- src/reducers/locations.js
Co-authored-by: Nazifa Hossain <44625143+ampers-and@users.noreply.github.com>
Co-authored-by: Christopher Pupo <cpupo822@gmail.com>
> Fixed errors how they were

- src/actions/locations.js
- src/components/SearchByCity.js
Co-authored-by: ChrisPupo22 <cpupo822@gmail.com>
Co-authored-by: Nazifa Hossain <zifi@ucla.edu>
> SeachByCity works without correct BE endpoint

- package.json
- yarn.lock
Co-authored-by: Nazifa Hossain <44625143+ampers-and@users.noreply.github.com>
Co-authored-by: Christopher Pupo <cpupo822@gmail.com>
> Installed material ui

- src/components/LandingPage.js
Co-authored-by: Nazifa Hossain <44625143+ampers-and@users.noreply.github.com>
Co-authored-by: Christopher Pupo <cpupo822@gmail.com>
> Gradient on hero image

- src/actions/factors.js
- src/components/CityCard.js
- src/components/SearchBar.js
Changed population to population_size
> Feature cycle2

- src/actions/deleteDislikedCity.js
- src/actions/deleteLikedCity.js
> FIXED DELETE SAVED

- src/components/CityCard.js
- src/components/CityPage.js
- src/components/Icon.js
- src/components/Modal.js
- src/components/MoreOptions.js
- src/utils/factors.js
Three button on city card to delete cities
> Feature show more text
